@config =
    templateBaseUrl: '/views/',
    bucket_uri: 'http://BUCKET_SERVER_URI/bucket/upload/',
    #loginBaseUrl: 'http://localhost:8002/api/v0',
    loginBaseUrl: 'http://data.nonetype.net/api/v0',
    useHtml5Mode: false,
    media_uri: 'http://MEDIA_SERVER/',
    rest_uri: "http://data.nonetype.net/api/v0",
    #rest_uri: "http://localhost:8002/api/v0"
