// Generated by CoffeeScript 1.4.0
(function() {

  angular.module('projectsheet', ['projectsheet.controllers', 'projectsheet.services', 'projectsheet.directives']);

  angular.module('makerscience', ['projectsheet', 'restangular', 'ui.bootstrap', 'ui.router']).config([
    '$httpProvider', function($httpProvider) {
      $httpProvider.defaults.useXDomain = true;
      return delete $httpProvider.defaults.headers.common['X-Requested-With'];
    }
  ]).config(function(RestangularProvider) {
    RestangularProvider.setBaseUrl(config.rest_uri);
    RestangularProvider.setRequestSuffix('?format=json');
    return RestangularProvider.setResponseExtractor(function(response, operation, what, url) {
      var newResponse;
      newResponse = null;
      if (operation === "getList") {
        newResponse = response.objects;
        newResponse.metadata = response.meta;
      } else {
        newResponse = response;
      }
      return newResponse;
    });
  }).config([
    '$locationProvider', '$stateProvider', '$urlRouterProvider', function($locationProvider, $stateProvider, $urlRouterProvider) {
      $locationProvider.html5Mode(config.useHtml5Mode);
      $urlRouterProvider.otherwise("/");
      return $stateProvider.state('project-list', {
        url: '/project',
        controller: 'ProjectListCtrl',
        templateUrl: 'views/projectsheet/project_list.html'
      }).state('project-detail', {
        url: '/projectsheet/:id',
        controller: 'ProjectDetailCtrl',
        templateUrl: 'views/projectsheet/project_detail.html'
      });
    }
  ]);

  console.debug("running makerscience...");

}).call(this);
