// Generated by CoffeeScript 1.4.0
(function() {
  var module;

  module = angular.module("projectsheet.controllers", ['projectsheet.services']);

  module.controller("ProjectListCtrl", function($scope, Project) {
    return $scope.projects = Project.getList().$object;
  });

  module.controller("ProjectSheetCtrl", function($scope, $stateParams, ProjectSheet, Project, PostalAddress, ProjectSheetTemplate, ProjectSheetItem) {
    return ProjectSheet.one().get({
      'project__slug': $stateParams.slug
    }).then(function(projectsheetResult) {
      var fillAnswer, projectID, templateID;
      $scope.projectsheet = projectsheetResult.objects[0];
      projectID = getObjectIdFromURI($scope.projectsheet.project);
      Project.one(projectID).get().then(function(projectResult) {
        var postalAddressId;
        $scope.projectsheet.project = projectResult;
        postalAddressId = getObjectIdFromURI($scope.projectsheet.project.location);
        return $scope.projectsheet.project.location = PostalAddress.one(postalAddressId).get().$object;
      });
      $scope.projectsheet.q_a = [];
      templateID = getObjectIdFromURI($scope.projectsheet.template);
      fillAnswer = function(question, i) {
        var itemID;
        itemID = getObjectIdFromURI($scope.projectsheet.items[i]);
        return ProjectSheetItem.one(itemID).get().then(function(itemResult) {
          var item;
          item = {
            'question': question,
            'answer': itemResult.answer
          };
          return $scope.projectsheet.q_a.push(item);
        });
      };
      return ProjectSheetTemplate.one(templateID).get().then(function(templateResult) {
        var i, question, _i, _len, _ref, _results;
        _ref = templateResult.questions;
        _results = [];
        for (i = _i = 0, _len = _ref.length; _i < _len; i = ++_i) {
          question = _ref[i];
          _results.push(fillAnswer(question, i));
        }
        return _results;
      });
    });
  });

}).call(this);
