// Generated by CoffeeScript 1.4.0
(function() {
  var module;

  module = angular.module("projectsheet.controllers", ['projectsheet.services']);

  module.controller("ProjectListCtrl", function($scope, Project) {
    return $scope.projects = Project.getList().$object;
  });

  module.controller("ProjectSheetCtrl", function($scope, $stateParams, ProjectSheet) {
    return ProjectSheet.one().get({
      'project__slug': $stateParams.slug
    }).then(function(res) {
      return $scope.projectsheet = res.objects[0];
    });
  });

}).call(this);
