// Generated by CoffeeScript 1.4.0
(function() {
  var module;

  module = angular.module("projectsheet.services", ['restangular']);

  module.factory('Project', function(Restangular) {
    return Restangular.service('project');
  });

  module.factory('ProjectSheet', function(Restangular) {
    return Restangular.service('projectsheet');
  });

  module.factory('PostalAddress', function(Restangular) {
    return Restangular.service('scout/postaladdress');
  });

  module.factory('ProjectSheetTemplate', function(Restangular) {
    return Restangular.service('projectsheettemplate');
  });

  module.factory('ProjectSheetItem', function(Restangular) {
    return Restangular.service('projectsheetsuggesteditem');
  });

}).call(this);
