// Generated by CoffeeScript 1.4.0
(function() {
  var module;

  module = angular.module("makerscience.catalog.controllers", []);

  module.controller("MakerscienceProjectSheetCreateCtrl", function($scope, $controller) {
    console.log("MakerscienceProjectSheetCreateCtrl");
    $controller('ProjectSheetCreateCtrl', {
      $scope: $scope
    });
    return $scope.loadTags = function(query) {
      var tags;
      tags = [
        {
          "text": "créativité",
          "text": "workshop",
          "text": "géologie",
          "text": "hydrologie",
          "text": "numérique",
          "text": "réalité",
          "text": "augmentée"
        }
      ];
      return tags;
    };
  });

}).call(this);
