// Generated by CoffeeScript 1.4.0
(function() {
  var module;

  module = angular.module("projectsheet.controllers", ['projectsheet.services']);

  module.controller("ProjectListCtrl", function($scope, ProjectSheet) {
    return $scope.projects = ProjectSheet.getList().$object;
  });

  module.controller("ProjectDetailCtrl", function($scope, $stateParams, ProjectSheet) {
    return $scope.project = ProjectSheet.one($stateParams.id).get().$object;
  });

}).call(this);
