// Generated by CoffeeScript 1.4.0
(function() {
  var module;

  module = angular.module('projectsheet.directives', []);

  module.directive('showonhoverparent', function() {
    var link;
    link = function(scope, element, attrs) {
      element.parent().bind('mouseenter', function() {
        return element.show();
      });
      return element.parent().bind('mouseleave', function() {
        return element.hide();
      });
    };
    return {
      restrict: 'A',
      link: link
    };
  });

}).call(this);
