// Generated by CoffeeScript 1.4.0
(function() {
  var module;

  module = angular.module("projectsheet.services", ['restangular']);

  module.factory('ProjectSheet', function(Restangular) {
    return Restangular.service('project/');
  });

}).call(this);
